services:
  pgdb:
    image: postgres
    container_name: pgdb
    restart: always
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - pg:/var/lib/postgresql/data
    networks:
      - my-network

  node_app:
    build: .
    container_name: node_app
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - pgdb
    networks:
      - my-network

  openssl:
    build: ./openssl
    volumes:
      - ssl-certs:/certs
    networks:
      - my-network

  nginx:
    container_name: nginx_app
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl-certs:/certs
    depends_on:
      - pgdb
      - node_app
      - openssl
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  pg:
  ssl-certs:
