services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: node
    build: .
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - .env

  openssl:
    build: ./openssl
    volumes:
      - ssl-certs:/certs

  nginx:
    container_name: nginx_app
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl-certs:/certs
    depends_on:
      - postgres
      - node
      - openssl

volumes:
  postgres-volume:
  ssl-certs:
