name: Pull Request on Github
on: [pull_request]
jobs:
  PullRequest-GitHub:
    runs-on: ubuntu-latest #github nos fornecerá a máquina.
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "gamebits_test"
          envkey_IGDB_CLIENT_ID: ${{ secrets.IGDB_CLIENT_ID }}
          envkey_IGDB_TOKEN: ${{ secrets.IGDB_TOKEN }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_DATABASE_URL: "postgresql://postgres:postgres@pgdb:5432/students_live"
          directory: ./
          file_name: .env.test
          fail_on_empty: true
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run node_app npm run test
